get_book:
    path: /book/{bookId}
    methods: GET
    controller: App\BookEditorBundle\Controller\GetBookController::getBook
    requirements:
        bookId: '\d+'

edit_book:
    path: /book/{bookId}
    methods: PATCH
    controller: App\BookEditorBundle\Controller\EditBookController::editBook
    requirements:
        bookId: '\d+'

get_chapter:
    path: /chapter/{chapterId}
    methods: GET
    controller: App\BookEditorBundle\Controller\GetChapterController::getChapter
    requirements:
        chapterId: '\d+'

edit_chapter:
    path: /chapter/{chapterId}
    methods: PATCH
    controller: App\BookEditorBundle\Controller\EditChapterController::editChapter
    requirements:
        chapterId: '\d+'

delete_chapter:
    path: /chapter/{chapterId}
    methods: DELETE
    controller: App\BookEditorBundle\Controller\DeleteChapterController::deleteChapter
    requirements:
        chapterId: '\d+'

get_paragraph:
    path: /paragraph/{paragraphId}
    methods: GET
    controller: App\BookEditorBundle\Controller\GetParagraphController::getParagraph
    requirements:
        paragraphId: '\d+'

edit_paragraph:
    path: /paragraph/{paragraphId}
    methods: PATCH
    controller: App\BookEditorBundle\Controller\EditParagraphController::editParagraph
    requirements:
        paragraphId: '\d+'

delete_paragraph:
    path: /paragraph/{paragraphId}
    methods: DELETE
    controller: App\BookEditorBundle\Controller\DeleteParagraphController::deleteParagraph
    requirements:
        paragraphId: '\d+'

edit_verse:
    path: /verse/{verseId}
    methods: PATCH
    controller: App\BookEditorBundle\Controller\EditVerseController::editVerse
    requirements:
        verseId: '\d+'

delete_verse:
    path: /verse/{verseId}
    methods: DELETE
    controller: App\BookEditorBundle\Controller\DeleteVerseController::deleteVerse
    requirements:
        verseId: '\d+'

