get_book:
    path: /book/{bookId}
    methods: GET
    controller: App\BookEditorBundle\Controller\GetBookController::getBook
    requirements:
        bookId: '\d+'

edit_book:
    path: /book/{bookId}
    methods: PATCH
    controller: App\BookEditorBundle\Controller\EditBookController::editBook

get_chapter:
    path: /chapter/{chapterId}
    methods: GET
    controller: App\BookEditorBundle\Controller\GetChapterController::getChapter
    requirements:
        chapterId: '\d+'

edit_chapter:
    path: /chapter/{chapterId}
    methods: PATCH
    controller: App\BookEditorBundle\Controller\EditChapterController::editChapter

get_paragraph:
    path: /paragraph/{paragraphId}
    methods: GET
    controller: App\BookEditorBundle\Controller\GetParagraphController::getParagraph
    requirements:
        paragraphId: '\d+'
